import { Quiz } from "../quiz";

export const MOCK_QUIZ: Quiz[] = [
    {
        name: "Quiz de Pedreiro",
        image: "../../../assets/images/quizimg_placeholder.jpg",
        description: "Você é um pedreiro de verdade ou apenas um poser? Responda este quiz e descubra",
        questions: ['Pergunta 1?', 'Pergunta 2?', 'Pergunta 3?'],
        answers: [['Resposta 1A', 'Resposta 1B', 'Resposta 1C', 'Resposta 1D'], ['Resposta 2A', 'Resposta 2B', 'Resposta 2C', 'Resposta 2D'], ['Resposta 3A', 'Resposta 3B', 'Resposta 3C', 'Resposta 3D']],
        correct_answers: [1, 3, 2],
        times_played: 200,
        ranked_players: 3,
        favorites: 30,
        category: "Profissões",
        tags: ["#Pedreiro", "#Emprego"],
        top_scores: [{ player: 'Player 1', score: 150 }, { player: 'Player2', score: 140 }, { player: 'Player3', score: 130 }],
    },
    {
        name: "Quiz de Açougueiro",
        image: "../../../assets/images/quizimg_placeholder2.jpg",
        description: "Você é um açougueiro de verdade ou apenas um poser? Responda este quiz e descubra",
        questions: ['Pergunta 1?', 'Pergunta 2?', 'Pergunta 3?'],
        answers: [['Resposta 1A', 'Resposta 1B', 'Resposta 1C', 'Resposta 1D'], ['Resposta 2A', 'Resposta 2B', 'Resposta 2C', 'Resposta 2D'], ['Resposta 3A', 'Resposta 3B', 'Resposta 3C', 'Resposta 3D']],
        correct_answers: [4, 4, 1],
        times_played: 400,
        ranked_players: 20,
        favorites: 100,
        category: "Profissões",
        tags: ["#Açougueiro", "#Emprego"],
        top_scores: [{ player: 'Player 1', score: 350 }, { player: 'Player2', score: 340 }, { player: 'Player3', score: 330 }],
    },
    {
        name: "Quiz de Padeiro",
        image: "../../../assets/images/quizimg_placeholder3.jpg",
        description: "Você é um padeiro de verdade ou apenas um poser? Responda este quiz e descubra",
        questions: ['Pergunta 1?', 'Pergunta 2?', 'Pergunta 3?'],
        answers: [['Resposta 1A', 'Resposta 1B', 'Resposta 1C', 'Resposta 1D'], ['Resposta 2A', 'Resposta 2B', 'Resposta 2C', 'Resposta 2D'], ['Resposta 3A', 'Resposta 3B', 'Resposta 3C', 'Resposta 3D']],
        correct_answers: [2, 4, 3],
        times_played: 200,
        ranked_players: 3,
        favorites: 30,
        category: "Profissões",
        tags: ["#Padeiro", "#Emprego"],
        top_scores: [{ player: 'Player 1', score: 200 }, { player: 'Player2', score: 190 }, { player: 'Player3', score: 160 }],
    },
]